sudo: required
services:
  - docker

before_install:
  - docker build -t ptviet/complex-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ptviet/complex-test npm test -- --coverage

after_success:
  - docker build -t ptviet/complex-client ./client
  - docker build -t ptviet/complex-nginx ./nginx
  - docker build -t ptviet/complex-server ./server
  - docker build -t ptviet/complex-worker ./worker
  # Login to docker cli
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push ptviet/complex-client
  - docker push ptviet/complex-nginx
  - docker push ptviet/complex-server
  - docker push ptviet/complex-worker
